export const SKILL_VOCABULARY = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "C++",
  "Go",
  "Rust",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Scala",
  "R",
  "SQL",
  "HTML",
  "CSS",
  "React",
  "Next.js",
  "Vue",
  "Angular",
  "Node.js",
  "Express",
  "NestJS",
  "Django",
  "Flask",
  "FastAPI",
  "Spring",
  "GraphQL",
  "REST",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Elasticsearch",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "GCP",
  "Terraform",
  "CI/CD",
  "Git",
  "Linux",
  "Agile",
  "Scrum",
  "Leadership",
  "Communication",
  "Problem Solving",
  "Teamwork",
  "Project Management",
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Data Analysis",
  "Pandas",
  "NumPy",
  "Tableau",
  "Power BI",
  "Figma",
  "UI/UX",
  "Testing",
  "Jest",
  "Playwright",
  "Cypress",
  "Microservices",
  "System Design",
  "API Design",
  "Security",
  "OAuth",
  "JWT",
  "Prisma",
  "TypeORM",
  "BullMQ",
  "RabbitMQ",
  "Kafka",
  "Webpack",
  "Vite",
  "Tailwind CSS",
  "Sass",
  "Bootstrap",
  "Mobile Development",
  "iOS",
  "Android",
  "React Native",
  "Flutter",
  "DevOps",
  "Monitoring",
  "Logging",
  "Performance Optimization",
  "Accessibility",
  "Technical Writing",
  "Mentoring",
  "Stakeholder Management",
  "Budgeting",
  "Negotiation",
  "Customer Service",
  "Sales",
  "Marketing",
  "SEO",
  "Content Strategy",
  "Public Speaking",
  "Research",
  "Statistics",
  "Excel",
  "Word",
  "PowerPoint",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Video Editing",
  "Copywriting",
  "Critical Thinking",
  "Time Management",
  "Adaptability",
  "Collaboration",
  "Attention to Detail",
] as const;
