import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const envPath = path.join(rootDir, ".env");
const examplePath = path.join(rootDir, ".env.example");
const webEnvPath = path.join(rootDir, "apps/web/.env.local");

const WEB_ENV_KEYS = [
  "AUTH_SECRET",
  "NEXTAUTH_URL",
  "NEXT_PUBLIC_API_URL",
  "DATABASE_URL",
];

function parseEnv(content) {
  const values = new Map();

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }

    const separator = trimmed.indexOf("=");
    if (separator === -1) {
      continue;
    }

    const key = trimmed.slice(0, separator).trim();
    const value = trimmed.slice(separator + 1).trim();
    values.set(key, value);
  }

  return values;
}

function serializeEnv(values, keys) {
  const lines = [
    "# Generated by scripts/setup-env.mjs — do not edit manually.",
    "# Re-run: pnpm setup:env",
    "",
  ];

  for (const key of keys) {
    const value = values.get(key);
    if (value !== undefined) {
      lines.push(`${key}=${value}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

if (!existsSync(envPath)) {
  if (!existsSync(examplePath)) {
    console.error("Missing .env and .env.example");
    process.exit(1);
  }

  writeFileSync(envPath, readFileSync(examplePath, "utf8"));
  console.log("Created .env from .env.example");
}

let rootContent = readFileSync(envPath, "utf8");
const values = parseEnv(rootContent);
const currentSecret = values.get("AUTH_SECRET")?.trim() ?? "";

if (currentSecret.length < 32) {
  const secret = randomBytes(32).toString("base64");
  values.set("AUTH_SECRET", secret);

  if (/^AUTH_SECRET=.*$/m.test(rootContent)) {
    rootContent = rootContent.replace(/^AUTH_SECRET=.*$/m, `AUTH_SECRET=${secret}`);
  } else {
    rootContent += `\nAUTH_SECRET=${secret}\n`;
  }

  writeFileSync(envPath, rootContent);
  console.log("Generated AUTH_SECRET in .env");
} else {
  console.log("AUTH_SECRET already set in .env");
}

writeFileSync(webEnvPath, serializeEnv(values, WEB_ENV_KEYS));
console.log("Synced apps/web/.env.local");
